---
name: Update Packages

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  find-recipes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout Submodules
        run: |
          mkdir -p ~/.ssh
          cat .github/known-hosts >> ~/.ssh/known_hosts
          git submodule update --init --recursive --remote

      - name: Find Updated Packages
        id: set-matrix
        run: |
          echo "matrix=$(./scripts/update.py --check --repo ./aur.archlinux.org)" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

  build:
    needs: find-recipes
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/robertrosca/aur-pkgs:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    if: '${{ needs.find-recipes.outputs.matrix != ''{"include": []}'' }}'
    strategy:
      matrix: ${{ fromJson(needs.find-recipes.outputs.matrix) }}
    name: Update "${{ matrix.package }}"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout Submodules
        run: |
          mkdir -p ~/.ssh
          cat .github/known-hosts >> ~/.ssh/known_hosts
          git submodule update --init --recursive --remote ${{ matrix.package }}

      - name: Update
        run: ./scripts/update.py ${{ matrix.package }} > COMMIT_MSG

      - name: Check
        run: cd ${{ matrix.package }} && makepkg -s --check --noprogressbar --noconfirm --nocolor --clean

      - name: Commit and Push
        run: |
          cd ${{ matrix.package }}
          git add PKGBUILD .SRCINFO
          git commit -m $msg
          git push
